---
- name: Pousser les modifications du dossier kevin/config vers le dépôt Git
  hosts: git
  become: yes
  vars:
    repo_path: "/home/kevin/config"
    log_file: "/home/kevin/backup_log/backup.log"
    max_log_size: 1

  tasks:
    - name: Vérifier que Git est installé
      command: git --version
      register: git_version
      failed_when: git_version.rc != 0
      changed_when: false

    - name: Créer le répertoire de log si nécessaire
      file:
        path: "{{ log_file | dirname }}"
        state: directory

    - name: Vérifier la taille du fichier de log et effectuer une rotation si nécessaire
      shell: |
        if [ -e "{{ log_file }}" ]; then
          LOG_SIZE_MB=$(du -m "{{ log_file }}" | awk '{print $1}')
          if [ "$LOG_SIZE_MB" -gt {{ max_log_size }} ]; then
            mv "{{ log_file }}" "{{ log_file }}.1"
            rm -f "{{ log_file }}.2"
            mv "{{ log_file }}.1" "{{ log_file }}.2"
          fi
        fi
      ignore_errors: yes

    - name: Afficher un message de début de sauvegarde
      debug:
        msg: "-----------------------------/!\\ Backup commencé le {{ ansible_date_time.iso8601 }} /!\\-----------------------------"

    - name: Changer de répertoire vers le répertoire Git et effectuer les commandes Git
      block:
        - name: Ajouter tous les fichiers modifiés à l'index Git
          git:
            repo: "{{ repo_path }}"
            state: present
            track: yes
            name: "backup"
            commit_msg: "Backup for {{ ansible_date_time.iso8601 }}"

        - name: Effectuer git push
          command: git push
          args:
            chdir: "{{ repo_path }}"
      ignore_errors: yes

    - name: Afficher un message de succès
      debug:
        msg: "-----------------------------/!\\ Backup effectué le {{ ansible_date_time.iso8601 }} /!\\-----------------------------"
