---
- name: Get Gluetun port
  hosts: portainer
  gather_facts: false
  tasks:
    - name: Get the Gluetun container port
      command: docker inspect -f '{{range .NetworkSettings.Ports}}{{.}}{{end}}' gluetun
      register: gluetun_port_output

    - name: Extract port number
      set_fact:
        gluetun_port: "{{ gluetun_port_output.stdout | regex_search(':(\\d+)', '\\1') }}"
