---
- name: Orchestrate Seedbox and Docker updates
  hosts: portainer
  gather_facts: false
  tasks:
    - name: Run playbook to get Gluetun port
      import_playbook: get_gluetun_port.yml

    - name: Run playbook to update .rtorrent.rc files
      import_playbook: update_rtorrent_rc.yml

    - name: Run playbook to update and restart Portainer stack
      import_playbook: update_portainer_stack.yml
